sudo: required

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export REPO=francoishill/mattermost-platform
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

env:
  global:
  - secure: XFxacdANyZ1LKV7j74eegmIZIkKD9OrAlo3XCo6l47t/gb58B9I7+as6nO+6YzcAEj9DyXkcnW18Hyqa3cOJmsm3sDknUzYMESUD/Z12ddOJXDDEGp9DuCR5ftl+QGOPr91rPlHXCeQnJ7hPi2rGPEp5UJhVF7tIwXbeJLYkrP67qK8gUB5Kd7lDYGHvrVSsE3h5OUZqff5rYPoz9Hjhqe7wG1S4NBs+Me7a8zItgkUA/ELjVBABO049gC5DbGM8JNsOrXvNXzicGKgvtC1Naw1px4Mib3tkDJypEhsaOeyIStXDL3vs3GUsE3R2oll59tyj0ndLt4tso6Ugwg+S7N6xyUljOFK08VEXJa/Yj/4GXUZrUMlFnXWwsbHCVru0y4V/2oseCHr5jcvC+4hDDsE8TANdZFXjS5eN6qgYu8SMpI8Jn1srYiLjZaR8h0UAwHGE1/hFm4NSeXdd/gvJvviD62/3VhPAzYVt2+XHIKLNWks85L4qNbDGgtEFZZbY1B/oujaUjxhQz0dA5Wnw1hJ8tJ1OhU4mluBVCii01Fkyb3OAumG6OCSjaRGrLVkwTNIK3dIPlq/EJkplPPfr3JOsg+orsDDwMTOPeeXEF+E2JcLEFRHsvYoPZATzjR2dfWUgykRrbQPc/TuwoHeq1G2uFDrMYNIwFacIxCVBRrk=
  - secure: SDcnbyZB6LMiCzY8eZ9InahfhZUzA8b/ukWkEcVMqPnFWeEfSA1qYP0dCMi7Vc0Hq56e5d99gd4cTCMJY7WakQ81TZCF+6XIsKvLlGYUHiBhNJgAYhXV5MF2MSFRe42JbO4xdXPqfx0c0oLjFqanIk8wiXOT02sGdANqRzL43Af+MNDh361jYY7fG2xQASrmdTWYDasfNNRkXQwZ5sp1P8MPq6Kst8jo8n/lYVAlJ80B1FSWGNkrRCtoPggAvy06xir34v4ukweumryBWgyxMOPzCfuOfEA2W2ur0I47w7K96aF8T5QAK6ldETizmfIqwWqH0R5ojP0IXi1KZNpQijleAD34mICDGPbthf3C499e7ISKGeAks7RsDs6oLXuMiIxFWeEpWfcM43eCDDLc5t2HCimdwKLcH4k1uuLla0mRvmwl2d5fwgUBWw4VTmt6t9fibZn8OPPq2zMZH/EhqVIcOYEhFeNEmo54iHoZ7ezksPV6S2inyrq8caT2DHSKtFU60UA1hCF1uAQ6qZQS7mDYUp3yLLr6pO2MW2i/LaRGr+RuvjKojnY2xWO8y8wyG9adzMDjwYxoCrkOET5xbXIpOyCLE4/MtAujWmG0cdl3SZ5+jOJNo3hOuZcrVMBQ3vSSpLyUvhcc3F9q+8f4QhWFJu7cVWRB85uAdSBujlk=
