sudo: required

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export REPO=francoishill/mattermost-platform
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

env:
  global:
  - DOCKER_USERNAME=francoishill
  - secure: N5XTKOm8OLsQZA1tuJYktnT4yDtm6mzjqLGMtoObclxeQ5jvbjq/lELNDu7Lgle8a093Nfhwxd4h6rJCv5bdIPtFX6XyL/imNcH1++3BPxhntIjsctyApYr5r/ugjuAGskpPzIeA92VWLY/ocFrInRuc7YaEO663zE0t9xBkiePQzensSXMNjeGGd2/1JHLXKF+MHuPWldrFgqcjItZK+q0cPq/1K37lL25ovt3J6nfsOp2uxfHatmMPMYH3iyTb93YvyuifRIuhvhx8xeSUg64he1urDPkjCyfJCQDAdUT6xsxEitBOrfAMOE2FNYrMT7ubSxJBoOuVL/tX7ckxkBUFD+sGufl9K9VFyOIYHGwrZH/XsLoYV/Re9qnERVcGb0vQvoRkclSCSMVuWOkb6FQhwkM2ARDujNHom/HH2Ml+IdazS6jcaVOB/BDIxLKwUDI68ecwhQZW8la1ZtL4NbxsRu1aUmRybFEWnat8Vy19V4D50gF/K1ycTw/PSdlu9ADBLjmmJmU0smEYgC7ohQ5sZurYi9IqJcbZS343vLcrn7UHfJbtvHPWeqthMsT12t+FrMKtSCAd4XGi3npB8x1XxDhsdS+jdyDzOFrRhzyqDj5vciEzTvGvDMH8qsc1zz100WCs//hLfEQuOZnwydxmKfPtBcUtiDnI7VhbJPI=
